apiVersion: v1
kind: BuildConfig
metadata:
  name: welcome-pipeline
  labels:
    name: welcome-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "welcome", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('welcome-pipeline') {\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'welcome')\nopenshiftScale(deploymentConfig: 'welcome',replicaCount: '2')\n}"
  output:
  resources:
  postCommit:
