apiVersion: v1
kind: BuildConfig
metadata:
  name: blue-pipeline
  labels:
    name: blue-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "blue", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node {\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'blue')\nopenshiftScale(deploymentConfig: 'blue',replicaCount: '2')\n}"
  output:
  resources:
  postCommit:
